# -*- coding: utf-8 -*-
"""Lab4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13IhWuu0Wi8jGXHNLJa9PdlajhzfNlhzU
"""

import tensorflow as tf
from tensorflow.keras.datasets import cifar10
import matplotlib.pyplot as plt
import numpy as np

(x_train, y_train), (x_test, y_test) = cifar10.load_data()

print("Training Images Shape :", x_train.shape)
print("Training Labels Shape :", y_train.shape)

print("Testing Images Shape :", x_test.shape)
print("Testing Labels Shape :", y_test.shape)

x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

class_names = [
    "Airplane",
    "Automobile",
    "Bird",
    "Cat",
    "Deer",
    "Dog",
    "Frog",
    "Horse",
    "Ship",
    "Truck"
]

plt.figure(figsize=(12, 5))

for i in range(10):
    plt.subplot(2, 5, i + 1)
    plt.imshow(x_train[i])
    plt.title(class_names[y_train[i][0]])
    plt.axis("off")

plt.tight_layout()
plt.show()

from tensorflow.keras.applications import VGG16

base_model = VGG16(
    weights="imagenet",
    include_top=False,
    input_shape=(32, 32, 3)
)

base_model.summary()

base_model.trainable = False

from tensorflow.keras import layers
from tensorflow.keras import models

model = models.Sequential([
    base_model,

    layers.GlobalAveragePooling2D(),

    layers.Dense(256, activation="relu"),

    layers.Dense(10, activation="softmax")
])

# Display model architecture
model.summary()

# Compile the model
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# Train the model
history = model.fit(
    x_train,
    y_train,
    validation_split=0.1,
    epochs=10,
    batch_size=32
)

import matplotlib.pyplot as plt

# Train the model
history = model.fit(
    x_train,
    y_train,
    validation_split=0.1,
    epochs=10,
    batch_size=32
)

# -------------------------------
# Training and Validation Accuracy
# -------------------------------

plt.figure(figsize=(8, 5))

plt.plot(
    history.history["accuracy"],
    label="Training Accuracy"
)

plt.plot(
    history.history["val_accuracy"],
    label="Validation Accuracy"
)

plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("Training and Validation Accuracy")
plt.legend()
plt.grid()

plt.show()


# -------------------------------
# Training and Validation Loss
# -------------------------------

plt.figure(figsize=(8, 5))

plt.plot(
    history.history["loss"],
    label="Training Loss"
)

plt.plot(
    history.history["val_loss"],
    label="Validation Loss"
)

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training and Validation Loss")
plt.legend()
plt.grid()

plt.show()


# -------------------------------
# Test Evaluation
# -------------------------------

test_loss, test_accuracy = model.evaluate(
    x_test,
    y_test,
    verbose=1
)

print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)
print("Test Accuracy (%):", test_accuracy * 100)


# Final training accuracy
final_training_accuracy = history.history["accuracy"][-1]

print(
    "Final Training Accuracy (%):",
    final_training_accuracy * 100
)

# ==========================================
# TASK 4: FINE-TUNING
# ==========================================

# Evaluate before fine-tuning
test_loss_before, test_accuracy_before = model.evaluate(
    x_test,
    y_test,
    verbose=0
)

print(
    "Test Accuracy Before Fine-Tuning:",
    test_accuracy_before * 100,
    "%"
)


# ------------------------------------------
# Unfreeze VGG16
# ------------------------------------------

base_model.trainable = True


# Freeze all layers first
for layer in base_model.layers:
    layer.trainable = False


# Unfreeze only Block 5
for layer in base_model.layers:
    if layer.name.startswith("block5"):
        layer.trainable = True


# Check trainable status
print("\nLayer Trainability:")

for layer in base_model.layers:
    print(layer.name, layer.trainable)


# ------------------------------------------
# Recompile with smaller learning rate
# ------------------------------------------

model.compile(
    optimizer=tf.keras.optimizers.Adam(
        learning_rate=0.0001
    ),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)


# ------------------------------------------
# Fine-tune
# ------------------------------------------

fine_tune_history = model.fit(
    x_train,
    y_train,
    validation_split=0.1,
    epochs=5,
    batch_size=32
)


# ------------------------------------------
# Evaluate after fine-tuning
# ------------------------------------------

test_loss_after, test_accuracy_after = model.evaluate(
    x_test,
    y_test,
    verbose=0
)

print(
    "\nTest Accuracy After Fine-Tuning:",
    test_accuracy_after * 100,
    "%"
)


# ------------------------------------------
# Calculate improvement
# ------------------------------------------

improvement = (
    test_accuracy_after - test_accuracy_before
) * 100

print(
    "Accuracy Improvement:",
    improvement,
    "%"
)


# ------------------------------------------
# Fine-Tuning Accuracy Plot
# ------------------------------------------

plt.figure(figsize=(8, 5))

plt.plot(
    fine_tune_history.history["accuracy"],
    label="Training Accuracy"
)

plt.plot(
    fine_tune_history.history["val_accuracy"],
    label="Validation Accuracy"
)

plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("Fine-Tuning Accuracy")
plt.legend()
plt.grid()

plt.show()


# ------------------------------------------
# Fine-Tuning Loss Plot
# ------------------------------------------

plt.figure(figsize=(8, 5))

plt.plot(
    fine_tune_history.history["loss"],
    label="Training Loss"
)

plt.plot(
    fine_tune_history.history["val_loss"],
    label="Validation Loss"
)

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Fine-Tuning Loss")
plt.legend()
plt.grid()

plt.show()

# ==========================================
# TASK 5: MODEL EVALUATION
# ==========================================

import numpy as np
import matplotlib.pyplot as plt

from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)


# ------------------------------------------
# Generate Predictions
# ------------------------------------------

y_pred_prob = model.predict(x_test)

# Convert probabilities to class numbers
y_pred = np.argmax(y_pred_prob, axis=1)

# Convert actual labels from (10000, 1)
# to (10000,)
y_true = y_test.flatten()


# ------------------------------------------
# Accuracy
# ------------------------------------------

test_loss, test_accuracy = model.evaluate(
    x_test,
    y_test,
    verbose=0
)


# ------------------------------------------
# Precision
# ------------------------------------------

precision = precision_score(
    y_true,
    y_pred,
    average="weighted"
)


# ------------------------------------------
# Recall
# ------------------------------------------

recall = recall_score(
    y_true,
    y_pred,
    average="weighted"
)


# ------------------------------------------
# F1 Score
# ------------------------------------------

f1 = f1_score(
    y_true,
    y_pred,
    average="weighted"
)


# ------------------------------------------
# Print Overall Metrics
# ------------------------------------------

print("\n========== PERFORMANCE METRICS ==========")

print("Accuracy :", test_accuracy * 100, "%")
print("Precision:", precision * 100, "%")
print("Recall   :", recall * 100, "%")
print("F1-score :", f1 * 100, "%")


# ------------------------------------------
# Classification Report
# ------------------------------------------

print("\n========== CLASSIFICATION REPORT ==========\n")

print(
    classification_report(
        y_true,
        y_pred,
        target_names=class_names
    )
)


# ------------------------------------------
# Confusion Matrix
# ------------------------------------------

cm = confusion_matrix(
    y_true,
    y_pred
)

print("\n========== CONFUSION MATRIX ==========\n")
print(cm)


# ------------------------------------------
# Plot Confusion Matrix
# ------------------------------------------

plt.figure(figsize=(10, 8))

plt.imshow(cm)

plt.title("Confusion Matrix")

plt.xlabel("Predicted Label")

plt.ylabel("True Label")

plt.xticks(
    range(10),
    class_names,
    rotation=45
)

plt.yticks(
    range(10),
    class_names
)

plt.colorbar()

plt.tight_layout()

plt.show()

def create_model(
    learning_rate=0.001,
    dense_units=256,
    optimizer_name="adam"
):

    base_model = VGG16(
        weights="imagenet",
        include_top=False,
        input_shape=(32, 32, 3)
    )

    base_model.trainable = False

    model = tf.keras.Sequential([
        base_model,
        tf.keras.layers.GlobalAveragePooling2D(),
        tf.keras.layers.Dense(
            dense_units,
            activation="relu"
        ),
        tf.keras.layers.Dense(
            10,
            activation="softmax"
        )
    ])

    if optimizer_name == "adam":

        optimizer = tf.keras.optimizers.Adam(
            learning_rate=learning_rate
        )

    elif optimizer_name == "sgd":

        optimizer = tf.keras.optimizers.SGD(
            learning_rate=learning_rate
        )

    model.compile(
        optimizer=optimizer,
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model

model_lr1 = create_model(
    learning_rate=0.001
)

history_lr1 = model_lr1.fit(
    x_train,
    y_train,
    validation_split=0.1,
    epochs=10,
    batch_size=32,
    verbose=1
)

loss_lr1, accuracy_lr1 = model_lr1.evaluate(
    x_test,
    y_test,
    verbose=0
)

print(
    "Learning Rate 0.001:",
    accuracy_lr1 * 100,
    "%"
)

loss_lr1, accuracy_lr1 = model_lr1.evaluate(
    x_test,
    y_test,
    verbose=0
)

print(
    "Learning Rate 0.001:",
    accuracy_lr1 * 100,
    "%"
)

loss_lr2, accuracy_lr2 = model_lr2.evaluate(
    x_test,
    y_test,
    verbose=0
)

print(
    "Learning Rate 0.0001:",
    accuracy_lr2 * 100,
    "%"
)

#batch size
model_b16 = create_model(
    learning_rate=0.001,
    dense_units=256,
    optimizer_name="adam"
)

history_b16 = model_b16.fit(
    x_train,
    y_train,
    validation_split=0.1,
    epochs=10,
    batch_size=16,
    verbose=1
)

_, accuracy_b16 = model_b16.evaluate(
    x_test,
    y_test,
    verbose=0
)

model_b32 = create_model(
    learning_rate=0.001,
    dense_units=256,
    optimizer_name="adam"
)

history_b32 = model_b32.fit(
    x_train,
    y_train,
    validation_split=0.1,
    epochs=10,
    batch_size=32,
    verbose=1
)

_, accuracy_b32 = model_b32.evaluate(
    x_test,
    y_test,
    verbose=0
)

model_b64 = create_model(
    learning_rate=0.001,
    dense_units=256,
    optimizer_name="adam"
)

history_b64 = model_b64.fit(
    x_train,
    y_train,
    validation_split=0.1,
    epochs=10,
    batch_size=64,
    verbose=1
)

_, accuracy_b64 = model_b64.evaluate(
    x_test,
    y_test,
    verbose=0
)

#optimizers study
model_adam = create_model(
    learning_rate=0.001,
    dense_units=256,
    optimizer_name="adam"
)

history_adam = model_adam.fit(
    x_train,
    y_train,
    validation_split=0.1,
    epochs=10,
    batch_size=32,
    verbose=1
)

_, accuracy_adam = model_adam.evaluate(
    x_test,
    y_test,
    verbose=0
)

model_adam = create_model(
    learning_rate=0.001,
    dense_units=256,
    optimizer_name="adam"
)

history_adam = model_adam.fit(
    x_train,
    y_train,
    validation_split=0.1,
    epochs=10,
    batch_size=32,
    verbose=1
)

_, accuracy_adam = model_adam.evaluate(
    x_test,
    y_test,
    verbose=0
)

print("Adam Accuracy:", accuracy_adam * 100, "%")
print("SGD Accuracy :", accuracy_sgd * 100, "%")

#dense units study
model_d128 = create_model(
    learning_rate=0.001,
    dense_units=128,
    optimizer_name="adam"
)

history_d128 = model_d128.fit(
    x_train,
    y_train,
    validation_split=0.1,
    epochs=10,
    batch_size=32,
    verbose=1
)

_, accuracy_d128 = model_d128.evaluate(
    x_test,
    y_test,
    verbose=0
)

model_d256 = create_model(
    learning_rate=0.001,
    dense_units=256,
    optimizer_name="adam"
)

history_d256 = model_d256.fit(
    x_train,
    y_train,
    validation_split=0.1,
    epochs=10,
    batch_size=32,
    verbose=1
)

_, accuracy_d256 = model_d256.evaluate(
    x_test,
    y_test,
    verbose=0
)

#Epoch study
model_e20 = create_model(
    learning_rate=0.001,
    dense_units=256,
    optimizer_name="adam"
)

history_e20 = model_e20.fit(
    x_train,
    y_train,
    validation_split=0.1,
    epochs=20,
    batch_size=32,
    verbose=1
)

_, accuracy_e20 = model_e20.evaluate(
    x_test,
    y_test,
    verbose=0
)

print(
    "20 Epoch Accuracy:",
    accuracy_e20 * 100,
    "%"
)

import tensorflow as tf
import numpy as np
import time

from tensorflow.keras import layers
from tensorflow.keras import models

def build_lenet():

    model = models.Sequential([

        layers.Conv2D(
            6,
            kernel_size=5,
            activation="tanh",
            padding="same",
            input_shape=(32, 32, 3)
        ),

        layers.AveragePooling2D(pool_size=2),

        layers.Conv2D(
            16,
            kernel_size=5,
            activation="tanh"
        ),

        layers.AveragePooling2D(pool_size=2),

        layers.Flatten(),

        layers.Dense(
            120,
            activation="tanh"
        ),

        layers.Dense(
            84,
            activation="tanh"
        ),

        layers.Dense(
            10,
            activation="softmax"
        )
    ])

    return model

lenet = build_lenet()

lenet.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

lenet.summary()

start_time = time.time()

history_lenet = lenet.fit(
    x_train,
    y_train,
    validation_split=0.1,
    epochs=10,
    batch_size=32,
    verbose=1
)

lenet_training_time = time.time() - start_time

lenet_loss, lenet_accuracy = lenet.evaluate(
    x_test,
    y_test,
    verbose=0
)

print(
    "LeNet Test Accuracy:",
    lenet_accuracy * 100,
    "%"
)

print(
    "LeNet Training Time:",
    lenet_training_time,
    "seconds"
)

def build_alexnet():

    model = models.Sequential([

        layers.Conv2D(
            96,
            kernel_size=3,
            padding="same",
            activation="relu",
            input_shape=(32, 32, 3)
        ),

        layers.MaxPooling2D(
            pool_size=2
        ),

        layers.Conv2D(
            256,
            kernel_size=3,
            padding="same",
            activation="relu"
        ),

        layers.MaxPooling2D(
            pool_size=2
        ),

        layers.Conv2D(
            384,
            kernel_size=3,
            padding="same",
            activation="relu"
        ),

        layers.Conv2D(
            384,
            kernel_size=3,
            padding="same",
            activation="relu"
        ),

        layers.Conv2D(
            256,
            kernel_size=3,
            padding="same",
            activation="relu"
        ),

        layers.MaxPooling2D(
            pool_size=2
        ),

        layers.Flatten(),

        layers.Dense(
            4096,
            activation="relu"
        ),

        layers.Dropout(0.5),

        layers.Dense(
            4096,
            activation="relu"
        ),

        layers.Dropout(0.5),

        layers.Dense(
            10,
            activation="softmax"
        )
    ])

    return model

layers.Dropout(0.5)

alexnet = build_alexnet()

alexnet.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

start_time = time.time()

history_alexnet = alexnet.fit(
    x_train,
    y_train,
    validation_split=0.1,
    epochs=10,
    batch_size=32,
    verbose=1
)

alexnet_training_time = time.time() - start_time

alexnet_loss, alexnet_accuracy = alexnet.evaluate(
    x_test,
    y_test,
    verbose=0
)

print(
    "AlexNet Test Accuracy:",
    alexnet_accuracy * 100,
    "%"
)

print(
    "AlexNet Training Time:",
    alexnet_training_time,
    "seconds"
)

from tensorflow.keras.applications import VGG16

vgg16 = VGG16(
    weights=None,
    include_top=False,
    input_shape=(32, 32, 3)
)

weights=None

vgg_model = models.Sequential([

    vgg16,

    layers.GlobalAveragePooling2D(),

    layers.Dense(
        256,
        activation="relu"
    ),

    layers.Dropout(0.5),

    layers.Dense(
        10,
        activation="softmax"
    )
])

vgg_model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

start_time = time.time()

history_vgg = vgg_model.fit(
    x_train,
    y_train,
    validation_split=0.1,
    epochs=10,
    batch_size=32,
    verbose=1
)

vgg_training_time = time.time() - start_time

vgg_loss, vgg_accuracy = vgg_model.evaluate(
    x_test,
    y_test,
    verbose=0
)

print(
    "VGG16 Test Accuracy:",
    vgg_accuracy * 100,
    "%"
)

print(
    "VGG16 Training Time:",
    vgg_training_time,
    "seconds"
)

def inception_module(x, filters):

    branch1 = layers.Conv2D(
        filters,
        1,
        padding="same",
        activation="relu"
    )(x)

    branch2 = layers.Conv2D(
        filters,
        3,
        padding="same",
        activation="relu"
    )(x)

    branch3 = layers.Conv2D(
        filters,
        5,
        padding="same",
        activation="relu"
    )(x)

    branch4 = layers.MaxPooling2D(
        pool_size=3,
        strides=1,
        padding="same"
    )(x)

    branch4 = layers.Conv2D(
        filters,
        1,
        padding="same",
        activation="relu"
    )(branch4)

    return layers.concatenate([
        branch1,
        branch2,
        branch3,
        branch4
    ])

inputs = layers.Input(
    shape=(32, 32, 3)
)

x = layers.Conv2D(
    64,
    3,
    padding="same",
    activation="relu"
)(inputs)

x = inception_module(
    x,
    32
)

x = layers.MaxPooling2D(
    pool_size=2
)(x)

x = inception_module(
    x,
    64
)

x = layers.MaxPooling2D(
    pool_size=2
)(x)

x = inception_module(
    x,
    64
)

x = layers.GlobalAveragePooling2D()(x)

x = layers.Dense(
    128,
    activation="relu"
)(x)

outputs = layers.Dense(
    10,
    activation="softmax"
)(x)

googlenet = models.Model(
    inputs=inputs,
    outputs=outputs
)

googlenet.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

start_time = time.time()

history_googlenet = googlenet.fit(
    x_train,
    y_train,
    validation_split=0.1,
    epochs=10,
    batch_size=32,
    verbose=1
)

googlenet_training_time = time.time() - start_time

googlenet_loss, googlenet_accuracy = googlenet.evaluate(
    x_test,
    y_test,
    verbose=0
)

print(
    "GoogleNet Test Accuracy:",
    googlenet_accuracy * 100,
    "%"
)

print(
    "GoogleNet Training Time:",
    googlenet_training_time,
    "seconds"
)

from tensorflow.keras.applications import ResNet50

resnet = ResNet50(
    weights=None,
    include_top=False,
    input_shape=(32, 32, 3)
)

resnet_model = models.Sequential([

    resnet,

    layers.GlobalAveragePooling2D(),

    layers.Dense(
        256,
        activation="relu"
    ),

    layers.Dropout(0.5),

    layers.Dense(
        10,
        activation="softmax"
    )
])

resnet_model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

start_time = time.time()

history_resnet = resnet_model.fit(
    x_train,
    y_train,
    validation_split=0.1,
    epochs=10,
    batch_size=32,
    verbose=1
)

resnet_training_time = time.time() - start_time

resnet_loss, resnet_accuracy = resnet_model.evaluate(
    x_test,
    y_test,
    verbose=0
)

print(
    "ResNet50 Test Accuracy:",
    resnet_accuracy * 100,
    "%"
)

print(
    "ResNet50 Training Time:",
    resnet_training_time,
    "seconds"
)

lenet_params = lenet.count_params()
alexnet_params = alexnet.count_params()
vgg_params = vgg_model.count_params()
googlenet_params = googlenet.count_params()
resnet_params = resnet_model.count_params()

print("LeNet parameters:", lenet_params)
print("AlexNet parameters:", alexnet_params)
print("VGG16 parameters:", vgg_params)
print("GoogleNet parameters:", googlenet_params)
print("ResNet50 parameters:", resnet_params)

results = [
    ["LeNet-5",
     lenet_params,
     lenet_accuracy * 100,
     lenet_training_time],

    ["AlexNet",
     alexnet_params,
     alexnet_accuracy * 100,
     alexnet_training_time],

    ["VGG16",
     vgg_params,
     vgg_accuracy * 100,
     vgg_training_time],

    ["GoogleNet",
     googlenet_params,
     googlenet_accuracy * 100,
     googlenet_training_time],

    ["ResNet50",
     resnet_params,
     resnet_accuracy * 100,
     resnet_training_time]
]

import pandas as pd

results_df = pd.DataFrame(
    results,
    columns=[
        "Model",
        "Parameters",
        "Accuracy (%)",
        "Training Time (seconds)"
    ]
)

print(results_df)

